b_adwords_click_performance:
    constraints:
        unique:
            - gclid
        not_null:
            - gclid

b_adwords_criteria_performance:
    constraints:
        unique:
            - id
        not_null:
            - id

b_adwords_accounts:
    constraints:
        unique:
            - account_id
        not_null:
            - account_id

b_adwords_ad_groups:
    constraints:
        unique:
            - ad_group_id
        not_null:
            - ad_group_id

b_adwords_ads:
    constraints:
        unique:
            - ad_id
        not_null:
            - ad_id

b_adwords_campaigns:
    constraints:
        unique:
            - campaign_id
        not_null:
            - campaign_id
